name: Fetch MSF Characters (API)

on:
  workflow_dispatch:

  # Toutes les 3 heures (Ã  xx:10)
  schedule:
    - cron: "10 */3 * * *"

permissions:
  contents: write

concurrency:
  group: fetch-characters
  cancel-in-progress: true

jobs:
  fetch-characters:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install || true

      - name: Run fetch script
        run: node scripts/fetch-characters.mjs

      - name: Commit & Push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add docs/data/msf-characters.json

          git diff --cached --quiet && echo "No changes" && exit 0

          git commit -m "Update msf-characters.json (auto 3h)"
          git push